version: '3'

services:
    mongo-wallet:
        image: mongo
        restart: always
        command: mongod --bind_ip 172.16.0.2 --port 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ILIACHALLENGE
        ports:
            - 27017:27017
        volumes:
            - ./mongo-wallet-data:/data/db
        networks:
            ilianetwork:
                ipv4_address: 172.16.0.2

    mongo-user:
        image: mongo
        restart: always
        command: mongod --bind_ip 172.16.0.3 --port 27018
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ILIACHALLENGE
        ports:
            - 27018:27018
        volumes:
            - ./mongo-user-data:/data/db
        networks:
            ilianetwork:
                ipv4_address: 172.16.0.3

    wallet:
        build: ./wallet
        restart: always
        command: sh -c "/wait && npm start"
        environment:
            PORT: 3001
            MONGO_URL: mongodb://root:ILIACHALLENGE@172.16.0.2:27017/iliachallenge
            WAIT_HOSTS: 172.16.0.2:27017
        volumes:
            - ./wallet/src:/srv/app/src
        ports:
            - 3001:3001
        depends_on:
            - mongo-wallet
        networks:
            ilianetwork:
                ipv4_address: 172.16.0.4

    user:
        build: ./user
        restart: always
        command: sh -c "/wait && npm start"
        environment:
            PORT: 3002
            MONGO_URL: mongodb://root:ILIACHALLENGE@172.16.0.3:27018/iliachallenge
            WAIT_HOSTS: 172.16.0.3:27018
        volumes:
            - ./user/src:/srv/app/src
        ports:
            - 3002:3002
        depends_on:
            - mongo-user
        networks:
            ilianetwork:
                ipv4_address: 172.16.0.5

    api:
        build: ./api
        command: sh -c "/wait && npm start"
        restart: always
        environment:
            PORT: 3000
            WAIT_HOSTS: 172.16.0.4:3001, 172.16.0.5:3002
        volumes:
            - ./api/src:/srv/app/src
        ports:
            - 3000:3000
        depends_on:
            - wallet
            - user
        networks:
            ilianetwork:
                ipv4_address: 172.16.0.6

networks:
    ilianetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24