version: '3'

services:

    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - 2121:2121
        networks:
            - ilia-challenge-network

    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - 9092:9092
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "user-request:1:1,user-response:1:1,wallet-request:1:1,wallet-response:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - ilia-challenge-network

    mongo-wallet:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ILIACHALLENGE
        ports:
            - 27018:27017
        volumes:
            - ./mongo-wallet-data:/data/db
        networks:
            - ilia-challenge-network
        command: --quiet

    mongo-user:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ILIACHALLENGE
        ports:
            - 27019:27017
        volumes:
            - ./mongo-user-data:/data/db
        networks:
            - ilia-challenge-network
        command: --quiet

    wallet:
        build: ./wallet
        restart: always
        command: npm start
        environment:
            PORT: 3001
        volumes:
            - ./wallet:/srv/app
            - /srv/app/node_modules
        ports:
            - 3001:3001
        networks:
            - ilia-challenge-network
        links:
            - mongo-wallet
            - kafka

    user:
        build: ./user
        command: npm start
        restart: always
        environment:
            PORT: 3002
        volumes:
            - ./user:/srv/app
            - /srv/app/node_modules
        ports:
            - 3002:3002
        networks:
            - ilia-challenge-network
        links:
            - mongo-user
            - kafka

    api:
        build: ./api
        command: npm start
        restart: always
        environment:
            PORT: 3000
        volumes:
            - ./api:/srv/app
            - /srv/app/node_modules
        ports:
            - 3000:3000
        networks:
            - ilia-challenge-network
        links:
            - wallet
            - user

networks:
    ilia-challenge-network:
        driver: bridge